[if sub_comment]
    [if subscribed_to_own_comment]
        Confirm subscription to your comment on: [sub_post_title_clip]
    [else]
        Confirm subscription to comment ID #[sub_comment_id] on: [sub_post_title_clip]
    [endif]
[else]
    Confirm subscription to: [sub_post_title_clip]
[endif]
